// window.Popper = require('popper.js').default;
// window.$ = window.jQuery = require('jquery');
// require('bootstrap');

import { createApp } from 'vue';
import App from './App.vue';
// import Vue from 'vue';
import router from './router.js';
import axios from 'axios';
import VueAxios from 'vue-axios';
import DateRangePicker from 'vue2-daterange-picker';
import 'vue2-daterange-picker/dist/vue2-daterange-picker.css';
import ToastPlugin from 'vue-toast-notification';
import 'vue-toast-notification/dist/theme-bootstrap.css';
import { ValidationProvider, ValidationObserver } from 'vee-validate';
// import VueSessionStorage from 'vue-sessionstorage';
import 'bootstrap/dist/js/bootstrap.js';
import 'bootstrap/dist/css/bootstrap.min.css';
require('@/assets/css/argon.css');
require('@/assets/css/responsive.css');
require('@/assets/css/dark-argon.css');
import LoaderComponent from './components/Common/LoaderComponent.vue';
import NavAndSideBar from './components/Navbar_and_Sidebar/NavAndSideBar.vue';
import TableComponent from './components/User/TableComponent.vue';

const app = createApp(App);
app.config.globalProperties.$api = process.env.VUE_APP_API;
app.use(router);
app.use(VueAxios, axios);
app.use(ToastPlugin);
// app.config.globalProperties.$session = VueSessionStorage;
// app.use(VueSessionStorage);
// Vue.use(VueSessionStorage);
// Vue.config.productionTip = false;
app.component('date-range-picker', DateRangePicker);
app.component('loader-component', LoaderComponent);
app.component('nav-and-side-bar', NavAndSideBar);
app.component('table-component', TableComponent);
app.component('ValidationProvider', ValidationProvider);
app.component('ValidationObserver', ValidationObserver);
app.mount('#app');
